// ============================================================================
// FormalGuard — ECDSA Functional Correctness Properties
// ============================================================================
// Property ID:  FG_ECDSA_FUNC_001
// Compliance:   PCI-DSS 3.5.1
//
// Verifies ECDSA signature generation and verification round-trip
// correctness.
//
// Copyright 2026 Thuvaragan Paramsothy, Sanchayan Paramsothy, Jananthan Paramsothy
// SPDX-License-Identifier: Apache-2.0
// ============================================================================

module fg_ecdsa_functional (
  fg_ecdsa_if.props ecdsa
);

  import fg_pkg::*;

  // ==========================================================================
  // FG_ECDSA_FUNC_001 — Sign-Verify Round-Trip Correctness
  // ==========================================================================
  // A signature generated by the signing operation must be successfully
  // verified by the verification operation using the corresponding
  // public key.
  //
  // Compliance: PCI-DSS 3.5.1
  // ==========================================================================

  // Capture signing outputs for round-trip verification
  logic [255:0] captured_hash;
  logic [255:0] captured_sig_r;
  logic [255:0] captured_sig_s;
  logic [255:0] captured_pub_x;
  logic [255:0] captured_pub_y;
  logic         sig_captured;
  logic         awaiting_verify;

  always_ff @(posedge ecdsa.clk or negedge ecdsa.rst_n) begin
    if (!ecdsa.rst_n) begin
      captured_hash  <= '0;
      captured_sig_r <= '0;
      captured_sig_s <= '0;
      captured_pub_x <= '0;
      captured_pub_y <= '0;
      sig_captured   <= 1'b0;
      awaiting_verify <= 1'b0;
    end else begin
      // Capture sign inputs
      if (ecdsa.start && ecdsa.mode_sign && !ecdsa.busy) begin
        captured_hash  <= ecdsa.message_hash;
        captured_pub_x <= ecdsa.public_key_x;
        captured_pub_y <= ecdsa.public_key_y;
        sig_captured   <= 1'b0;
        awaiting_verify <= 1'b0;
      end
      // Capture signature output
      if (ecdsa.done && !ecdsa.error && ecdsa.mode_sign) begin
        captured_sig_r <= ecdsa.sig_r;
        captured_sig_s <= ecdsa.sig_s;
        sig_captured   <= 1'b1;
      end
      // Track verify of captured signature
      if (ecdsa.start && !ecdsa.mode_sign && sig_captured &&
          ecdsa.message_hash == captured_hash &&
          ecdsa.sig_r == captured_sig_r &&
          ecdsa.sig_s == captured_sig_s &&
          ecdsa.public_key_x == captured_pub_x &&
          ecdsa.public_key_y == captured_pub_y) begin
        awaiting_verify <= 1'b1;
      end
      if (ecdsa.done && awaiting_verify) begin
        awaiting_verify <= 1'b0;
        sig_captured    <= 1'b0;
      end
    end
  end

  property p_ecdsa_func_001;
    @(posedge ecdsa.clk) disable iff (!ecdsa.rst_n)
    (ecdsa.done && !ecdsa.error && awaiting_verify)
    |-> ecdsa.sig_valid;
  endproperty

  FG_ECDSA_FUNC_001: assert property (p_ecdsa_func_001)
    else $error("FG_ECDSA_FUNC_001 FAIL: Verify(Sign(M)) did not succeed — signature round-trip broken");

  // Operation must complete within bounded time
  property p_ecdsa_func_001_completion;
    @(posedge ecdsa.clk) disable iff (!ecdsa.rst_n)
    (ecdsa.start && !ecdsa.busy)
    |-> ##[1:FG_ECDSA_MAX_LATENCY] ecdsa.done;
  endproperty

  FG_ECDSA_FUNC_001_COMP: assert property (p_ecdsa_func_001_completion)
    else $error("FG_ECDSA_FUNC_001 FAIL: ECDSA did not complete within %0d cycles",
                FG_ECDSA_MAX_LATENCY);

  // Signature components must be non-zero on successful sign
  property p_ecdsa_func_001_nonzero;
    @(posedge ecdsa.clk) disable iff (!ecdsa.rst_n)
    (ecdsa.done && !ecdsa.error && ecdsa.mode_sign)
    |-> (ecdsa.sig_r != '0 && ecdsa.sig_s != '0);
  endproperty

  FG_ECDSA_FUNC_001_NZ: assert property (p_ecdsa_func_001_nonzero)
    else $error("FG_ECDSA_FUNC_001 FAIL: Signature has zero component (r=0 or s=0)");

  // ==========================================================================
  // Coverage
  // ==========================================================================

  cover property (@(posedge ecdsa.clk) ecdsa.start && ecdsa.mode_sign && !ecdsa.busy);
  cover property (@(posedge ecdsa.clk) ecdsa.done && !ecdsa.error && ecdsa.mode_sign);
  cover property (@(posedge ecdsa.clk) ecdsa.done && awaiting_verify && ecdsa.sig_valid);

endmodule : fg_ecdsa_functional
