// ============================================================================
// FormalGuard — ECDSA Nonce Security Properties
// ============================================================================
// Property IDs: FG_ECDSA_NONCE_001, FG_ECDSA_NONCE_002
// Compliance:   Critical (private key leak), FIPS 186-5
//
// Verifies that ECDSA nonces are never reused and are generated from
// an approved DRBG source. Nonce reuse in ECDSA is catastrophic —
// it allows trivial recovery of the private key.
//
// Copyright 2026 Thuvaragan Paramsothy, Sanchayan Paramsothy, Jananthan Paramsothy
// SPDX-License-Identifier: Apache-2.0
// ============================================================================

module fg_ecdsa_nonce (
  fg_ecdsa_if.props ecdsa
);

  import fg_pkg::*;

  // ==========================================================================
  // FG_ECDSA_NONCE_001 — No Nonce Reuse
  // ==========================================================================
  // The nonce k must NEVER repeat across two signing operations. If
  // k1 == k2 for two different messages, the private key can be
  // recovered via: d = (s1*m2 - s2*m1) / (s1*k - s2*k)
  //
  // This is the single most critical ECDSA property. Real-world
  // exploits: PlayStation 3 (2010), Bitcoin wallet thefts, many others.
  //
  // Compliance: Critical — nonce reuse leaks private key
  // ==========================================================================

  property p_ecdsa_nonce_001;
    @(posedge ecdsa.clk) disable iff (!ecdsa.rst_n)
    // When a signing operation completes, the nonce must differ from
    // the previous signing operation's nonce
    (ecdsa.done && !ecdsa.error && ecdsa.mode_sign &&
     ecdsa.prev_nonce_valid)
    |-> (ecdsa.nonce_k != ecdsa.prev_nonce);
  endproperty

  FG_ECDSA_NONCE_001: assert property (p_ecdsa_nonce_001)
    else $error("FG_ECDSA_NONCE_001 CRITICAL FAIL: Nonce reuse detected! Private key is compromised.");

  // Nonce must not be zero (degenerate case)
  property p_ecdsa_nonce_001_nonzero;
    @(posedge ecdsa.clk) disable iff (!ecdsa.rst_n)
    (ecdsa.done && !ecdsa.error && ecdsa.mode_sign)
    |-> (ecdsa.nonce_k != '0);
  endproperty

  FG_ECDSA_NONCE_001_NZ: assert property (p_ecdsa_nonce_001_nonzero)
    else $error("FG_ECDSA_NONCE_001 FAIL: Nonce is zero — degenerate signature");

  // Nonce must not equal the private key (trivially breakable)
  property p_ecdsa_nonce_001_not_key;
    @(posedge ecdsa.clk) disable iff (!ecdsa.rst_n)
    (ecdsa.done && !ecdsa.error && ecdsa.mode_sign)
    |-> (ecdsa.nonce_k != ecdsa.private_key);
  endproperty

  FG_ECDSA_NONCE_001_NK: assert property (p_ecdsa_nonce_001_not_key)
    else $error("FG_ECDSA_NONCE_001 FAIL: Nonce equals private key — trivially breakable");

  // ==========================================================================
  // FG_ECDSA_NONCE_002 — Approved DRBG Source
  // ==========================================================================
  // The nonce must be generated by an approved Deterministic Random Bit
  // Generator (DRBG), not from a static value, counter, or predictable
  // source. The nonce_from_drbg flag indicates the nonce source.
  //
  // Compliance: FIPS 186-5
  // ==========================================================================

  property p_ecdsa_nonce_002;
    @(posedge ecdsa.clk) disable iff (!ecdsa.rst_n)
    (ecdsa.done && !ecdsa.error && ecdsa.mode_sign)
    |-> ecdsa.nonce_from_drbg;
  endproperty

  FG_ECDSA_NONCE_002: assert property (p_ecdsa_nonce_002)
    else $error("FG_ECDSA_NONCE_002 FAIL: Nonce not from approved DRBG — predictable nonce vulnerability");

  // ==========================================================================
  // Coverage
  // ==========================================================================

  cover property (@(posedge ecdsa.clk) ecdsa.done && ecdsa.mode_sign && ecdsa.prev_nonce_valid);
  cover property (@(posedge ecdsa.clk) ecdsa.done && ecdsa.mode_sign && ecdsa.nonce_from_drbg);

endmodule : fg_ecdsa_nonce
