// ============================================================================
// FormalGuard — ECDSA Binding Interface
// ============================================================================
// Standardized interface for binding FormalGuard ECDSA verification
// properties to any ECDSA signing/verification implementation.
//
// Copyright 2026 Thuvaragan Paramsothy, Sanchayan Paramsothy, Jananthan Paramsothy
// SPDX-License-Identifier: Apache-2.0
// ============================================================================

interface fg_ecdsa_if;

  import fg_pkg::*;

  // Clock and Reset
  logic         clk;
  logic         rst_n;

  // Control
  logic         start;
  logic         done;
  logic         busy;
  logic         error;
  logic         mode_sign;      // 1 = sign, 0 = verify

  // Key Material
  logic [255:0] private_key;    // Private key (signing)
  logic [255:0] public_key_x;   // Public key X coordinate
  logic [255:0] public_key_y;   // Public key Y coordinate

  // Data
  logic [255:0] message_hash;   // Hash of the message to sign/verify

  // Signature
  logic [255:0] sig_r;          // Signature component r
  logic [255:0] sig_s;          // Signature component s
  logic         sig_valid;      // Signature is valid (verify mode)

  // Nonce (critical for security)
  logic [255:0] nonce_k;        // Nonce used in signing
  logic         nonce_from_drbg; // Nonce was generated by approved DRBG

  // Observation
  logic [255:0] prev_nonce;     // Nonce from previous signing operation
  logic         prev_nonce_valid; // Previous nonce is available for comparison

  // Clocking Block
  clocking cb @(posedge clk);
    input rst_n;
    input start, done, busy, error, mode_sign;
    input private_key, public_key_x, public_key_y;
    input message_hash, sig_r, sig_s, sig_valid;
    input nonce_k, nonce_from_drbg;
    input prev_nonce, prev_nonce_valid;
  endclocking

  modport props (
    input  clk, rst_n,
    input  start, done, busy, error, mode_sign,
    input  private_key, public_key_x, public_key_y,
    input  message_hash, sig_r, sig_s, sig_valid,
    input  nonce_k, nonce_from_drbg,
    input  prev_nonce, prev_nonce_valid,
    clocking cb
  );

  modport dut (
    input  clk, rst_n,
    input  start, mode_sign,
    input  private_key, public_key_x, public_key_y,
    input  message_hash,
    output done, busy, error,
    output sig_r, sig_s, sig_valid,
    output nonce_k, nonce_from_drbg,
    output prev_nonce, prev_nonce_valid
  );

endinterface : fg_ecdsa_if
